// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-cVuR8CYTz-bKJSMEYTzRymdEz7rVHHo',
    appId: '1:372432227943:web:fcc1df547d346cd4724ec2',
    messagingSenderId: '372432227943',
    projectId: 'one-day-69b78',
    authDomain: 'one-day-69b78.firebaseapp.com',
    storageBucket: 'one-day-69b78.firebasestorage.app',
    measurementId: 'G-1DC1HN8PZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Dozip4YRABXWoDDVTUUJY766NjrHrXs',
    appId: '1:372432227943:android:c62ec12253a2fd1d724ec2',
    messagingSenderId: '372432227943',
    projectId: 'one-day-69b78',
    storageBucket: 'one-day-69b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBkV_RjfvSiKDeFSt0p7XB5LNHO2ox8g',
    appId: '1:372432227943:ios:3e4b2d780ead3127724ec2',
    messagingSenderId: '372432227943',
    projectId: 'one-day-69b78',
    storageBucket: 'one-day-69b78.firebasestorage.app',
    iosBundleId: 'com.example.oneDayEmployees',
  );
}
